### ISSUE TITLE
Stub page for Project allocations

### ISSUE THREAD

**Issue by jafrahm** [ResearchComputing/mump#3]
Regarding this page:
https://portals.rc.colorado.edu/allocation/request/project/

We do not want people trying to request Summit allocations or even Janus allocations at this time.  
I'd like to remove the form and simply say:

> During the final weeks of Janus operation and in preparation for the transition to Summit please email rc-help@colorado.edu for any Janus allocation needs.  More information on Summit allocations is forthcoming on the RC website and RC Announcement email list, <rc-announce-join@colorado.edu>

The Startup page can remain as-is.
Thanks,
-J.

**Comment by anderbubble** [comment]
@zebulasampedro and I talked about this a bit, and we're going to see if we can get SIS to just use apache to stub the url out, overriding the application. To that end, we'll generate a static HTML page, give it to SIS, and see if they can update the apache config to display that page at https://portals.rc.colorado.edu/allocation/request/project/.

**Comment by jafrahm** [comment]
Hmm, that seems like a roundabout way to edit a page on a site where we already manage the content.
What would you do if we needed to fix a typo on that page?

**Comment by anderbubble** [comment]
We don't want to take on responsibility for making changes to deprecated code that is in the process of being decommissioned. It's safer to stub the dynamic page out with a static page than it is to update the code.

If we need to make changes the the page, I suspect we would edit the aforementioned static HTML page.

**Comment by jafrahm** [comment]
OK, you could also just edit the text above the form asking people not to use the Project form at this time if you do not want to comment out the form-related code.   We have safely made edits to the HTML text portion of this page int he past leaving the Python unaffected.

It's this page on Nemesis:
/data/web/projects/rcamp/apps/porkbelly/templates/allocationrequest.html
